# An unique identifier for the head node and workers of this cluster.
cluster_name: mlops-team50

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: us-west1
    availability_zone: us-west1-a
    project_id: daring-pilot-403921

available_node_types:
    ray_head_default:
        resources: {"CPU": 2}
    ray_worker_small:
        min_workers: 0
        max_workers: 2
        resources: {"CPU": 2}
